### ISSUE TITLE
Randomization of SVM's gp_regs 

### ISSUE THREAD

**Issue by bows7ring** [TwinVisor/twinvisor-prototype#1]
Thanks for open-sourcing! The paper is awesome, and I'm tring to delve deeper into this work.

However I have some questions regarding the implementation details. For instance, in the paper, it is mentioned,  `To prevent the N-visor from reading or writing register values, the Svisor saves all VM register values into its secure memory and randomizes general-purpose register values before redirecting a VM exit to the N-visor.`

But I couldn't find any relevant code for randomization, neither in the `restore_guest_states` nor in the `fastpath` parts.

I would like to seek information about the specific implementation details of gp_regs randomization. Was this aspect implemented separately, or was it omitted during the development of the fastpath version?

Thank you!

**Comment by 130B848** [comment]
Thanks for your interest in our work.

The design of randomization mentioned in the paper aims to prevent the leakage of guest data in gp-regs.

In the implementation of this open-sourced repository, we intentionally limit the exposure of register values to the untrusted host side. Specifically, we only expose necessary register values through current_vcpu_ctx.gp_regs.x[] (for instance, in [the mmio case](https://github.com/TwinVisor/s-visor/blob/e25e1a826f1c64363c4a3029ed149fedc65eb0c8/virt/vm.c#L208)). Consequently, any other exposed values are either initial or stale data, which is indeterminate and thus *randomized* to some extent. 

Alternatively, one can also implement a random number generator to populate these exposed values.

**Comment by bows7ring** [comment]
Alright, understood. Thanks for your reply! 🙏
